
---
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run: npm install
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: jest --collectCoverage=true
      - store_artifacts:
          path: coverage
