
---
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:current
    parallelism: 3
    steps:
      - checkout
      - run: npm install
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: |
            TESTFILES=$(circleci tests glob "./*.test.js" | circleci tests split --split-by=timings)
            echo $TESTFILES
            npx jest --coverageDirectory="coverage/${CIRCLE_NODE_INDEX}" $TESTFILES
      - store_artifacts:
          path: coverage
      - persist_to_workspace:
          root: ./
          paths:
            - coverage
  coverage:
    docker:
      - image: cimg/node:current
    steps:
      - attach_workspace:
          at: ./
      - run: ls coverage
      - run: cat coverage/coverage-final.json

workflows:
  build-coverage:
    jobs:
      - build
      - coverage:
          requires:
            - build
